-- Clean database

DROP TABLE CLICK IF EXISTS;
DROP TABLE SHORTURL IF EXISTS;
DROP TABLE USER IF EXISTS;
DROP TABLE USERSHORT IF EXISTS;

-- ShortURL

CREATE TABLE SHORTURL(
	HASH		VARCHAR(30) PRIMARY KEY,	-- Key
	TARGET		VARCHAR(1024),			-- Original URL
	SPONSOR		VARCHAR(1024),			-- Sponsor URL
	CREATED 	TIMESTAMP,			-- Creation date
	OWNER		VARCHAR(255),			-- User id
	MODE		INTEGER,			-- Redirect mode
	SAFE		BOOLEAN,			-- Safe target
	IP		VARCHAR(20),			-- IP
	COUNTRY		VARCHAR(50)			-- Country
);

-- Click

CREATE TABLE CLICK(
    	ID 			BIGINT IDENTITY,			-- KEY
	HASH 		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	-- Foreing key	
	CREATED 	TIMESTAMP,					-- Creation date
	REFERRER	VARCHAR(1024),				-- Traffic origin
	BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP		VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50)					-- Country
);

CREATE TABLE USER(
	USERNAME 	VARCHAR(30) NOT NULL PRIMARY KEY,
	PASSWORD 	VARCHAR(30) NOT NULL,
	EMAIL	 	VARCHAR(30) NOT NULL,
    	ROL		VARCHAR(30) NOT NULL,
	NAME		VARCHAR(30) NOT NULL,
);

CREATE TABLE USERSHORT(
	SHORTURL VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),
	USER     VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES USER(USERNAME),
	CONSTRAINT  USERSHORT_PK PRIMARY KEY (SHORTURL, USER)
); 
